stations_to_remove = [
    "Elephant & Castle",
    "Borough",
    "Moorgate",
    "Old Street",
    "Angel",
    "Hanger Lane",
    "Perivale",
    "Greenford",
    "Northolt",
    "South Ruislip",
    "Ruislip Gardens",
    "West Ruislip",
    "Ealing Common",
    "North Ealing",
    "Park Royal",
    "Alperton",
    "Sudbury Town",
    "Sudbury Hill",
    "South Harrow",
    "Rayners Lane",
    "Eastcote",
    "Ruislip Manor",
    "Ruislip",
    "Ickenham",
    "Hillingdon",
    "Uxbridge",
]
